/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.deephathi.crack.code;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
